title: CV | A Bhaskara Ram
description:  My Personal Curriculum Vitae/Resume
url: 
baseurl: 
theme_skin: red

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
