title: CV | A Bhaskara Ram
description:  My CV.
url: https://cv.bhaskarvilles.dev
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
