title: CV | A Bhaskara Ram
description:  My CV.
url: https://bhaskarvilles.github.io/jekyll-cv/
baseurl: 'https://bhaskarvilles.github.io/jekyll-cv/'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
